spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: Waver@4036
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
